### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Conaws** [boxed/instar#19]
I noticed the dependencies are out of date, and it's been a while since there has been a commit.  Is this a viable alternative to specter?

**Comment by boxed** [comment]
Well... We have no known bugs and the features we'd like to add have no way we've figured out to make them nice. 

Yea, the dependencies are out of date. Mostly because I don't do clojure professionally right now. Send me a PR and I'll merge it and make you a contributor probably :P
