### ISSUE TITLE
Getting path items?

### ISSUE THREAD

**Issue by LispEngineer** [boxed/instar#20]
Sorry to trouble the instar maintenance team. First, thank you for instar. I really love the ability to use it as a sort of "map path" transformation language with the *. It's been very helpful.

I have a question, though. It might be a feature request, or maybe a misunderstanding. Thank you for your indulgence in considering it.

I am trying to figure out how to pass the key matched by a * in to the transformation function. So, for example, imagine:

```clojure
(def x {:objects
   {:a {:type :npc :script "a.script"} 
  :b {:type :object :script "b.script"} 
  :c {:script "c.script"} 
  :npc {:script "d.script"}}})
```

I can get all the `:type` keys (and return new ones) with a `(transform x [:objects * :type] ...)`.

What I would like to do, however, is transform that type in this way:

a. If it exists, do nothing
b. If it doesn't exist, set `:type` to `:npc` if the key of that innermost map is `:npc`, otherwise set it to `:object`.

In other words, I effectively want the innermost `:type` key to always be present, and if not present, have it default to `:object` unless the outer key is `:npc`. This means I need to know the whole transformation path (the part inside the vector) as an input to the transformation function.

I have played around with `%%` and `%>` a bunch of times (using functions like `(fn [& rest] (println rest) (last rest))` to see what's going on viscerally) but can't figure out how to get the `:a`, `:b`, `:c`, or `:npc` tag into the transformation function. Is this even possible?

For example, putting `(%> *)` in place of the `*` in the transform above gives me the *value* of the matched `*` at that point (i.e., the map that contains or doesn't contain a :type), rather than the matched KEY itself.

Maybe this is a combination of `transform` with `get-in-paths`, something like a new `transform-with-path` or somesuch?

Thanks for any thoughts.

**Comment by crisptrutski** [comment]
Hi there! 

"Maintenance team" 😀  Note sure what the status is of this project anymore but thought I'd poke my head in.

I don't think what you want is possible - and if I can stick my head out of a bit (because I think it was my fault), the capture itself is just half baked and would be simple to improve.

Looking at performing this update directly, it's not /too/ byzantine..

```
(reduce (fn [acc id] (update-in acc [:objects id :type] #(or % (if (= :npc id) id :object)))) x (keys (:objects x)))
```

But not exactly simple to read either. What could it look like?

```
(instar/transform x [:objects '(*) :type] (fn [id t] (or t (if (= :npc id) id :object))))
```

Leaning on a "regex" style syntax for capturing the path. Or it could be a symbol like `>%`, "on the left like the key, not the right like the value". Would that mean needing a "capture" both? Or is capture value actually less natural/common than capture key?

The cynic in me wonders whether this isn't all already elegant in spectre already? :D Haven't followed it.

**Comment by boxed** [comment]
Maybe something simple like adding a new operator 
```
 (%key> *)
```

It's a bit ugly, but it's fairly explicit. I'll accept that it's ugly if it's uncommon. We should then introduce `%key%` to be consistent...

As for spectre... reading the docs seems like they don't have anything close to the powerful capture system instar does actually.

**Comment by boxed** [comment]
@crisptrutski Yea, the status seems to be "it's done and awesome" :P Mostly thanks to the hard work the "maintenance team" (that doesn't include me!) put in.

**Comment by LispEngineer** [comment]
Thanks for the discussion. I never saw [spectre](https://github.com/nathanmarz/specter) before but that's definitely now going into my Clojure toolbox. Cheers!

**Comment by boxed** [comment]
There are some other libs filling sort of the same niche as instar. Can't remember any of the other names right now though :P

**Comment by LispEngineer** [comment]
I guess, in the face of the `specter` library (not spectre), the question would be: How can you transform an item whilst being provided the exact path to get the item as an additional input into the transformer function.

It's like asking for a `transform-indexed` that is akin to the standard Clojure `map-indexed`.

**Comment by LispEngineer** [comment]
See [Specter issue](https://github.com/nathanmarz/specter/issues/169) - this is resolved there. Thanks.

**Comment by boxed** [comment]
I've thought about it and I think you can sort of do it in instar too by using expand-path first, then applying those. It's not super pretty, but I think ok if you do decide to stay with instar :P
